version: '3.8'

services:
  web:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434

  ollama:
    image: ollama/ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data: